#!/bin/sh

# Create symlinks:

SCRIPT=$(which $0)

file_link() {
  if [ -a "$2" ] && ! [ -h "$2" ]; then
    if [ -a "$2" ]; then
      echo "Is file";
    fi
    if ! [ -h "$2" ]; then
      echo "Is not symlink";
    fi
    echo "<${2}> already exists.  Remove and run again."
    return
  fi
  if ! [ -f "$1" ]; then
    echo "Cannot link to <${1}>!  File does not exist."
    return
  fi
  if [ -h "$2" ] && [ "$(readlink $2)" == "$1" ]; then
    return
  fi
  ln -s "$1" "$2"
}

dir_link() {
  if [ -a "$2" ] && ! [ -h "$2" ]; then
    echo "<${2}> already exists.  Remove and run again."
    return
  fi
  if ! [ -d "$1" ]; then
    echo "Cannot link to <${1}>!  Directory does not exist."
    return
  fi
  if [ -h "$2" ] && [ "$(readlink $2)" == "$1" ]; then
    return
  fi
  ln -s "$1" "$2"
}

dir_link .dotfiles/vim ~/.vim
file_link .dotfiles/bash/bashrc ~/.bashrc
file_link .dotfiles/bash/bashrc ~/.bash_profile
file_link .dotfiles/bash/aliases ~/.bash_aliases
file_link .dotfiles/inputrc ~/.inputrc
file_link .dotfiles/editrc ~/.editrc
file_link .dotfiles/crontab ~/.crontab
file_link .dotfiles/tmux/outer.conf ~/.tmux-outer.conf
file_link .dotfiles/tmux/shared.conf ~/.tmux-shared.conf
file_link .dotfiles/tmux/inner.conf ~/.tmux-inner.conf
file_link .vim/vimrc ~/.vimrc
