#!/bin/sh

SCRIPT=$(which $0)
DOTFILES="${SCRIPT%/script/setup}"
SCRIPTS="${DOTFILES}/script.d"

[ -d "${SCRIPTS}" ] || exit


echo "Checking ${SCRIPTS}: $(ls "${SCRIPTS}")"
for S_FILE in $(ls "${SCRIPTS}"); do
  echo "Script: <${S_FILE}>"
  if [ -f "${SCRIPTS}/${S_FILE}" ] && [ -x "${SCRIPTS}/${S_FILE}" ]; then
    echo "Running Script: <${S_FILE}>"
    "${SCRIPTS}/${S_FILE}"
  fi
done

